version: '3'
services:
  web_server:
    build: .
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
      - '1234:1234'
    environment:
      RAILS_ENV: development